# Site settings
title: David's Portfolio
email: onefunkybluesman@gmail.com
description: "David's Graphic/Web Design and Digital Goodness"
twitter_username: zioneyemedia
github_username: zioneyemedia
baseurl: "/portfolio"

# Build settings
markdown: kramdown
permalink: pretty
